name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/mygitdemo
          git pull
          pip3 install -r requirements.txt
          # Stop any old running version of the app
          pkill -f "python3 app.py" || true
          # Start the app in the background
          nohup python3 app.py > app.log 2>&1 &
