name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/mygitdemo
          git pull origin main

          # Install venv package
          sudo apt-get update -y
          sudo apt-get install -y python3.12-venv

          # Create and use virtual environment
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          # Stop any old process
          pkill -f "venv/bin/python app.py" || true
          
          # Start the app in the background
          nohup venv/bin/python app.py > app.log 2>&1 &

          # ==> FIX IS HERE <==
          # Wait for 2 seconds to let the process stabilize
          sleep 2
