name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/mygitdemo
          # Solution for Git Error: Specify the remote and branch
          git pull origin main

          # Solution for Python Error: Create and use a virtual environment
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          # Stop any old process
          pkill -f "venv/bin/python app.py" || true
          
          # Start the app using the python from the virtual environment
          nohup venv/bin/python app.py > app.log 2>&1 &
