name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/mygitdemo
          git pull origin main

          # ==> FIX IS HERE <==
          # Step 1: Install the package needed to create virtual environments
          sudo apt-get update -y
          sudo apt-get install -y python3.12-venv

          # Step 2: Now create and use the virtual environment
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          # Step 3: Stop any old process
          pkill -f "venv/bin/python app.py" || true
          
          # Step 4: Start the app using python from the virtual environment
          nohup venv/bin/python app.py > app.log 2>&1 &
